approve_by_comment: true
approve_regex: '^(Approved|:\+1:)'
reset_on_push: true
reviewers:
    required: 1
    members:
        - job13er
        - psbanka
        - sandersky
        - cstolli
        - agonza40
        - rajcoss
        - sophypal
